[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
v8 = "0.46.0"
scan_dir = "0.3.3"
walkdir = "2.3.2"